#include <hdPbrt/debugCodes.h>

PXR_NAMESPACE_OPEN_SCOPE

TF_REGISTRY_FUNCTION( TfDebug )
{
    TF_DEBUG_ENVIRONMENT_SYMBOL( HDPBRT_GENERAL, "HdPbrt general debug logging." );
}

PXR_NAMESPACE_CLOSE_SCOPE
