#include <hdPbr/debugCodes.h>

PXR_NAMESPACE_OPEN_SCOPE

TF_REGISTRY_FUNCTION( TfDebug )
{
    TF_DEBUG_ENVIRONMENT_SYMBOL( HDPBR_GENERAL, "HdPbr general debug logging." );
}

PXR_NAMESPACE_CLOSE_SCOPE
